// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyAIyMNBQvCnkEGHu6q4GyFeJaw-9vi9xiE',
  appId: '1:644879530474:web:484ff07e1a51fe99869a93',
  messagingSenderId: '644879530474',
  projectId: 'sehha-app-84ede',
  authDomain: 'sehha-app-84ede.firebaseapp.com',
  storageBucket: 'sehha-app-84ede.firebasestorage.app',
  measurementId: 'G-SB6YD7HN5F',
  databaseURL: 'https://sehha-app-84ede-default-rtdb.firebaseio.com', 
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBC2udHRxOCGZznn_IhghEWeAFxMpVXoQ',
    appId: '1:644879530474:android:e59b85daca176b4c869a93',
    messagingSenderId: '644879530474',
    projectId: 'sehha-app-84ede',
    storageBucket: 'sehha-app-84ede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pYP11kmFdJddrbZiXdcKgxkLYRE_y1A',
    appId: '1:644879530474:ios:84b73df0dd09d79c869a93',
    messagingSenderId: '644879530474',
    projectId: 'sehha-app-84ede',
    storageBucket: 'sehha-app-84ede.firebasestorage.app',
    iosBundleId: 'com.example.sehhaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7pYP11kmFdJddrbZiXdcKgxkLYRE_y1A',
    appId: '1:644879530474:ios:84b73df0dd09d79c869a93',
    messagingSenderId: '644879530474',
    projectId: 'sehha-app-84ede',
    storageBucket: 'sehha-app-84ede.firebasestorage.app',
    iosBundleId: 'com.example.sehhaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIyMNBQvCnkEGHu6q4GyFeJaw-9vi9xiE',
    appId: '1:644879530474:web:5c1a585aff8ea7a1869a93',
    messagingSenderId: '644879530474',
    projectId: 'sehha-app-84ede',
    authDomain: 'sehha-app-84ede.firebaseapp.com',
    storageBucket: 'sehha-app-84ede.firebasestorage.app',
    measurementId: 'G-NE01RC3QWY',
  );
}
